### ISSUE TITLE
[BUG]  No Audio (Only Dummy Device)

### ISSUE THREAD

**Issue by afzl-wtu** [mylinuxforwork/dotfiles#133]
**Describe the bug**
I moved from nixos where every thing was working on GNOME. I installed arch with
```
 linux-firmware linux-zen pipewire  pipewire-alsa pipewire-pulse pipewire-jack wireplumber
```
on both HP Elitebook 840 G6. But sound is not working at all. Only speaker shows dummy output on waybar.

**Distribution (please complete the following information):**
 - Arch Linux

**Comment by afzl-wtu** [comment]
By installing 
```
sof-firmware
```
and rebooting and then setting speak port instead of HDMI port  and muting and unmuting fixed sound issue.

**Comment by mylinuxforwork** [comment]
Thanks for providing your feedback.

**Comment by pendula95** [comment]
I have a similar issue. I installed sof-firmware straight away and tested sound worked before installing via you guide @mylinuxforwork 
After installation wrong profile/card is selected by default. To make my sound work I first need to select off in the list and then select speak in the list and repeat this multiple times until it works. Settings is forgotten after restart. Is there a way to make this permanent?

![image](https://github.com/user-attachments/assets/505f956a-54d0-49fb-97b5-af0fcbc6b133)

**Comment by afzl-wtu** [comment]
@pendula95 instead you should go to Output Devices section. And search for your physical speaker device. click on Mute and then unmute it. I manage to get my audio in this way every time I restart my PC

**Comment by mylinuxforwork** [comment]
Can you try this https://www.reddit.com/r/archlinux/comments/m7yc6j/pipewire_0324_no_audio_devices_found/

And you're not able to set the audio device with pavucontrol?

**Comment by pendula95** [comment]
> @pendula95 instead you should go to Output Devices section. And search for your physical speaker device. click on Mute and then unmute it. I manage to get my audio in this way every time I restart my PC

But I don't want to do this every time I restart my laptop. This should be done automatically and correct device should be selected.   

> Can you try this https://www.reddit.com/r/archlinux/comments/m7yc6j/pipewire_0324_no_audio_devices_found/
And you're not able to set the audio device with pavucontrol?

No, I can see the correct device but it is not selected by default. I have installed arch minimal installation with pipewire as server and after installation installed sof-firmware. Checked sound and it was working. I checked and pipewire has correct default device configured. Marked with * but for some reason pavucontrol sets the wrong one. I can not find any config file of pavucontrol so I thought you have some insight where the issue might be.
![image](https://github.com/user-attachments/assets/d966f8c6-4e58-476e-bed9-c159eb908a75)


Pavucontrol came with hyprland dotfiles so it might be that more audio stuff was installed that might be conflicting. What are the packages installed besides pavucontrol that might affect audio settings.

**Comment by pendula95** [comment]
Well a little update. Seems that the original assumption that wrong profile is selected is not true. The issue is FN mute and unmute buttons on keyboard. And it has a strange behavior.  My fn controls are working that is tested but on bott something is out of sync. On my keyboard both microphone and speaker mute buttons (F1 and F4) have a light indicator which signals that they are muted. This is correctly shown on waybar or in the settings. If I toggel mute on keyboard once the light stays on and the now it is reflected in waybar that the speakers are muted. If toggle it again I unmute it and everything works then as expected. To fight this I have added following in custom configuration:
```
exec-once = pactl set-source-mute @DEFAULT_SOURCE@ toggle
exec-once = wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
exec-once = wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
```
This will result on boot: 
1) Speakers are unmuted and working
2) Microphone is muted but now is reflected correctly in settings and ui

I guess the issue is most likely with kernel or arch but do you have any idea what could be the issue? @mylinuxforwork
