### ISSUE TITLE
[FEATURE] Add kitty dotfiles

### ISSUE THREAD

**Issue by mylinuxforwork** [mylinuxforwork/dotfiles#291]
**Is your feature request related to a problem? Please describe.**
Add kitty dotfiles to the configuration

**Describe the solution you'd like**
In addition to Alacritty, users requested kitty as a terminal.

**Comment by soulstirrings** [comment]
Yes, @mylinuxforwork, most people want kitty because it can render some Pokémon color script or similar shell programs to make it looks aesthetically pleasing. 

I recommend [https://github.com/acxz/pokeshell](url) this concept implemented in kitty theming and config and also integrated with hyfetch which is better than fastfetch, where if one opens the terminal, it automatically fetches system info via hyfetch. 

I hope you check out this project and implement it. Thank-you in advance.

**Comment by mylinuxforwork** [comment]
@soulstirrings Great input. Will definitely check it out.
