### ISSUE TITLE
[BUG] Nautilus/GTK borders

### ISSUE THREAD

**Issue by 4ndril** [mylinuxforwork/dotfiles#329]
Black border when using Nautilus but not in Thunar

**To Reproduce**
1. Go to 'Nautilus'
2. Right Click in the window
4. See the black border in the screenshot.

**Screenshots**
[screenshot123_15102024_100936](https://github.com/user-attachments/assets/c8135491-76a0-47d5-b9d0-730b610ea235)

 - Arch Linux
 - ML4W from fresh install from GitLab days

**Comment by mylinuxforwork** [comment]
I will check.

**Comment by mylinuxforwork** [comment]
![image](https://github.com/user-attachments/assets/98994651-2671-4258-823f-53ee109bfe1a)

Tested on my system. Works on my system without the border. Can you check the environment variables on your system?

# Ozone
env = OZONE_PLATFORM,wayland
env = ELECTRON_OZONE_PLATFORM_HINT,wayland

But not sure if this is the solution.

**Comment by Yot360** [comment]
Hello, I also have this issue, and I check and the env variables are in the config so that's not the issue. 
![image](https://github.com/user-attachments/assets/56bf4cbb-15ee-49b8-af39-c538be87ce9a)

The app is also running using wayland as we can see by running `hyprctl clients`.
![image](https://github.com/user-attachments/assets/ab063c93-62cb-45d0-9f20-b1e0fee68666)

**Comment by mylinuxforwork** [comment]
I have not the issue on all of my systems. Do you have an NVIDIA card? Just an assumption.

**Comment by Yot360** [comment]
> I have not the issue on all of my systems. Do you have an NVIDIA card? Just an assumption.

I have an AMD card, so that's probably not the issue either.
