### ISSUE TITLE
[FEATURE] Post install script

### ISSUE THREAD

**Issue by bknightInfo** [mylinuxforwork/dotfiles#36]
Hi @mylinuxforwork,

I have readded my request from gitlab but in a hopefully simpler way of doing a post install script as sometimes the hooks.js isnt enough to get the customisation into your system.

Things for a script a post install script
* adjust install applications (removing and adding)
* adjusting dotfiles  (removing and adding)
* adjusting services
* additional configuration

An example of my script  after ml4w installation is https://github.com/bknightInfo/hyprland-dotsv2/blob/main/update.sh but would love to simplified version more in line with your project. 

but if you think hyprland-start would be a better place to start with this I am OK with this request being closed.

**Comment by mylinuxforwork** [comment]
Thank you. I will definitely add a post script. When do you want to get the post script executed? Just before the reboot dialogue?

I am planning to provide a hook.tpl, an automation.tpl and a post.tlp in the dotfiles-versions folder. The scripts can be activated by renaming them to *.sh

The automation.sh would be a configuration to completely run the dotfiles update automatilly and skip all confirmation dialogues.

I am also thinking about preparing helper functions e.g., protect FILE/FOLDER instead of rm for removing a files used in the hook.sh

What do you think?

**Comment by mylinuxforwork** [comment]
@bknightInfo Have added a post.sh support to the main branch. In addition a optimized the installer and the hook.sh with new features. https://github.com/mylinuxforwork/dotfiles/wiki/Hook-and-Post-Installation-Scripts 

Just run the installer again to get the latest versions. Thanks again for this request.
