### ISSUE TITLE
[BUG] No mouse cursor on Vmware Workstation using Arch

### ISSUE THREAD

**Issue by bkdwt** [mylinuxforwork/dotfiles#65]
Hello! I testing your dotfiles on Arch installed on Vmware Workstation. Everything has installed successfully, but I don't have a mouse cursor and your keyboard binds doesn't work (my keyboard layout is configured correctly).

This is my first time with WM. There's something to do to mouse cursor works or maybe this is a bug with Vmware? I have tested with Plasma 6.1.3 and works without problem.
![Captura de tela 2024-07-26 114724](https://github.com/user-attachments/assets/7ab718e2-f52d-4b9b-8aa0-206b3e130406)

**Comment by mylinuxforwork** [comment]
@bkdwt In general, Hyprland is not made for VMs. The performance is very laggy. I use QEMU/KVM (with enabled 3D acceleration) for testing the dotfiles. The performance is enough for testing purposes.
Never installed it in VMWare or VirtualBox.

That's why it's difficult to support you here. But let's have this issue open for a while. Maybe another user can support here.

**Comment by bkdwt** [comment]
> @bkdwt In general, Hyprland is not made for VMs. The performance is very laggy. I use QEMU/KVM (with enabled 3D acceleration) for testing the dotfiles. The performance is enough for testing purposes. Never installed it in VMWare or VirtualBox.
> 
> That's why it's difficult to support you here. But let's have this issue open for a while. Maybe another user can support here.

Yeah, this is a problem with VM. I have tested on bare metal and everything works like a charm. ;)

**Comment by mylinuxforwork** [comment]
Thanks for your feedback.
